spring:
  profiles:
    active: dev

  cloud:
    compatibility-verifier:
      enabled: false
    config:
      label: latest

  config:
    import: configserver:http://localhost:8888
  application:
    name: config-consumer
server:
  port: 8081

